language: java

jdk:
  - openjdk16

sudo: false

env:
  global:
    - CODECOV_TOKEN=76ff0adf-8707-4772-886e-1f2fb57d3016

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always